name: Populate External Source Code

on:
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Force fetch submodules
        run: |
          git submodule update --init --recursive --force

      - name: Convert Submodules to Real Folders
        run: |
          rm -f .gitmodules
          git rm --cached -r Natives/external/ || true
          find Natives/external -name ".git" -exec rm -rf {} +

      - name: Commit and Push to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Natives/external/ -f
          git commit -m "chore: Ép thêm mã nguồn vật lý tại Natives/external/" || true
          git push