name: Populate External Source Code

on:
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Convert Submodules to Real Folders
        run: |
          rm -f .gitmodules
          git rm --cached -r Natives/external/ || true
          find Natives/external -name ".git" -type d -exec rm -rf {} +
          find Natives/external -name ".git" -type f -exec rm -rf {} +

      - name: Commit and Push to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Natives/external/
          git add .gitmodules || true
          git commit -m "chore: Chuyển đổi submodule thành mã nguồn vật lý tại Natives/external/" || true
          git push